In [ ]:
import numpy as np

# creating arrays
a = np.array([1, 2, 3])                     # 1D vector
b = np.array([[1, 2, 3], [4, 5, 6]])        # 2D matrix (2x3)
zeros = np.zeros((3, 4))                    # 3x4 matrix of zeros
ones = np.ones((2, 3))
random = np.random.randn(3, 3)              # standard normal
identity = np.eye(3)                        # 3x3 identity matrix


In [4]:
# shape and dtype
print(a.shape)
print(b.shape)
print(a.dtype)

(3,)
(2, 3)
int64


In [ ]:
# Indexing and Slicing
print(b[0, 1])          # 2 (row 0, col 1)
print(b[:, 1])          # [2, 5] (all rows, col 1)
print(b[0, :])          # [1, 2, 3] (row 0, all cols)

2
[2 5]
[1 2 3]


In [7]:
# Reshaping
flat = np.arange(12)            # [0,1,2,...,11]
matrix = flat.reshape(3, 4)     # 3x4 matrix
back = matrix.flatten()         # back to 1D

In [ ]:
# Basic operations (element-wise)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)       
print(x * 2)       
print(x ** 2)      

[5 7 9]
[2 4 6]
[1 4 9]


In [9]:
# Aggregation
data = np.array([1, 2, 3, 4, 5])
print(data.sum())
print(data.mean())
print(data.std())
print((data.min()), data.max())


15
3.0
1.4142135623730951
1 5


In [10]:
# Boolean Indexing (critical for ML)
arr = np.array([1, -2, 3, -4, 5])
positive = arr[arr > 0] 
print(positive)

[1 3 5]


In [23]:
# Practice
dt = np.random.randn(5, 5)          # random 5x5 matrix
print(dt)
print('---------------------')
print(dt.diagonal())                # print diagonal elements
print('---------------------')
row_means = np.mean(dt, axis = 1)   # compute mean of each row
print(row_means)

[[ 1.07863296 -1.5623382  -0.02976593 -0.83571651  0.64868657]
 [-1.28439987  0.58727595 -0.93805984  0.54443643 -1.3382987 ]
 [ 1.06147556  0.96736162 -0.61262266  0.50647452 -1.86819579]
 [ 1.27424958  2.14802965 -1.11648544  0.43024754  0.02231638]
 [ 0.26061423  1.08550076 -0.15946753  0.14863458  1.39299816]]
---------------------
[ 1.07863296  0.58727595 -0.61262266  0.43024754  1.39299816]
---------------------
[-0.14010022 -0.4858092   0.01089865  0.55167154  0.54565604]
